require("mason-tool-installer").setup({
    ensure_installed = {
        "gopls",
        "delve",
        "golangci-lint",
        "gomodifytags",
        "goimports",
        "impl",
        "gotests",
        "cmake-language-server",
        "cmakelint",
        "python-lsp-server",
        "ruff",
        "markdownlint",
        "stylua",
        "lua-language-server",
        "yamlfmt",
        "cpplint",
        "shfmt",
        "shellcheck",
        "bash-language-server",
    },
    run_on_start = true,
})
